services:
  db:
    image: ankane/pgvector            # already has pgvector extension
    container_name: pgvector-db
    ports:
      - "6543:5432"   # hostPort:containerPort
    environment:
      POSTGRES_DB: agentdb            # << database name you want
      POSTGRES_USER: postgres         # default superuser
      POSTGRES_PASSWORD: password     # << keep in .env too
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d  # mounts SQL init dir
