version: '3.9'

services:
  db:
    image: ankane/pgvector    # pgvector-ready Postgres image
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: agentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
